//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ателье
{
    using System;
    using System.Collections.Generic;
    
    public partial class Изделия_с_фурнитурой
    {
        public string Артикул_фурнитуры { get; set; }
        public string Артикул_продукта { get; set; }
        public string Размещение { get; set; }
        public Nullable<decimal> Ширина { get; set; }
        public Nullable<decimal> Длина { get; set; }
        public Nullable<decimal> Поворот { get; set; }
        public int Количество { get; set; }
    
        public virtual Фурнитура Фурнитура { get; set; }
        public virtual Продукт Продукт { get; set; }
    }
}
