//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ателье
{
    using System;
    using System.Collections.Generic;
    
    public partial class Фурнитура
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Фурнитура()
        {
            this.Изделия_с_фурнитурой = new HashSet<Изделия_с_фурнитурой>();
            this.Склад_фурнитуры = new HashSet<Склад_фурнитуры>();
        }
    
        public string Артикул_фурнитуры { get; set; }
        public string Название { get; set; }
        public string Тип { get; set; }
        public Nullable<decimal> Ширина { get; set; }
        public Nullable<decimal> Длинна { get; set; }
        public Nullable<decimal> Вес { get; set; }
        public string Картинка { get; set; }
        public Nullable<decimal> Цена { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Изделия_с_фурнитурой> Изделия_с_фурнитурой { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Склад_фурнитуры> Склад_фурнитуры { get; set; }
    }
}
